name: Dendron

on:
  push:
    branches:
    - main
  # Run every hour
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout & update submodules
      run: git submodule update --init --recursive --remote

    - name: Install npm dependencies
      run: yarn

    - name: Generate docs
      run: yarn dendron-cli importPod --wsRoot . --podId dendron.markdown

    - name: Push changes
      uses: EndBug/add-and-commit@v7.0.0
      with:
        message: "autoupdate docs"
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Build pod
      run: yarn dendron-cli buildSiteV2 --wsRoot .  --stage prod

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true
        cname: "tldr.dendron.so"
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
